#!/usr/bin/env bash
#This script transfers a file from our client to a server


if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

file="$1"
host="$2"
user="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file" "$user@$host:~/"
