#!/usr/bin/env bash
# This script installs and configures Nginx on a new Ubuntu machine


apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
