#!/usr/bin/env bash
# This script configures your Nginx server so that /redirect_me is redirecting to another page


apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /redirect_me {
		return 304 https://www.google.com;
	}
}
" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
