#!/usr/bin/env bash
# This script configures your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page


apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404-error.html
echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	error_page 404 /var/www/html/404-error.html;

	location = /var/www/html/404-error.html; {
		internal;
	}

	location /redirect_me {
		return 304 https://www.google.com;
	}
}
" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
