#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using a
# loop + IFS, as a story.

while IFS= read -r line
do
	username=$(echo "$line" | cut -d ":" -f 1)
	password=$(echo "$line" | cut -d ":" -f 2)
	user_id=$(echo "$line" | cut -d ":" -f 3)
	group_id=$(echo "$line" | cut -d ":" -f 4)
	user_id_info=$(echo "$line" | cut -d ":" -f 5)
	home_dir=$(echo "$line" | cut -d ":" -f 6)
	shell=$(echo "$line" | cut -d ":" -f 7)

	echo The user "$username" is part of the "$group_id" gang, lives in "$home_dir" and rides "$shell". "$user_id"\'s place is protected by the passcode "$password", more info about the user here: "$user_id_info"
done < /etc/passwd
