#!/usr/bin/env bash
# This script displays "Best School" 10 times, but the 9th iteration displays "Hi"

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	(( i++ ))
done
