#!/usr/bin/env bash
# This script loops from 1 to 10 and:
# displays "bad luck" on the 4th iteration
# displays "good luck" on the 8th iteration
# displays "Best School" for the other iterations

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
