#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/new_hosts

sed -e '/\tlocalhost/c 127.0.0.2	localhost' -e '/\tfacebook.com/c 8.8.8.8	facebook.com' /etc/hosts > ~/new_hosts 

cp -f ~/new_hosts /etc/hosts
